doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Enraged\Xenomorph\Application:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/application'
                prefix: 'Enraged\Xenomorph\Application'
            Enraged\Xenomorph\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/domain'
                prefix: 'Enraged\Xenomorph\Domain'
            Enraged\Xenomorph\Infrastructure:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/orm/infrastructure'
                prefix: 'Enraged\Xenomorph\Infrastructure'
