framework:
    messenger:
        reset_on_message: true
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

        default_bus: application_command.bus
        buses:
          application_command.bus:
            middleware:
              - Enraged\Xenomorph\Infrastructure\BUS\Middleware\AuditMiddleware
              - dispatch_after_current_bus
              - doctrine_transaction
          application_query.bus:
            middleware:
              - Enraged\Xenomorph\Infrastructure\BUS\Middleware\AuditMiddleware
          application_event.bus:
            default_middleware: allow_no_handlers
            middleware:
              - Enraged\Xenomorph\Infrastructure\BUS\Middleware\AuditMiddleware
              - dispatch_after_current_bus
          domain_event.bus:
              default_middleware: allow_no_handlers
              middleware:
                  - Enraged\Xenomorph\Infrastructure\BUS\Middleware\AuditMiddleware
                  - dispatch_after_current_bus