version: "3.3"

services:
  application:
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
###< symfony/mailer ###
