services:
    application:
        namespace: Enraged\Xenomorph\Application\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application'
        autowire: false
        autoconfigure: false
        exclude:
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Command/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Query/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Event/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Assertion/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Exception/'

    # APPLICATION/COMMAND HANDLERS
    application_commands:
        namespace: Enraged\Xenomorph\Application\Command\
        autowire: false
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Command/'

    application_command_handlers:
        namespace: Enraged\Xenomorph\Application\CommandHandler\
        autowire: true
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/CommandHandler/'
        tags: [ { name: 'messenger.message_handler', bus: 'command.bus' } ]

    # APPLICATION/QUERY HANDLERS
    application_queries:
        namespace: Enraged\Xenomorph\Application\Query\
        autowire: false
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Query/'

    query_handlers:
        namespace: Enraged\Xenomorph\Application\QueryHandler\
        autowire: true
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/QueryHandler/'
        tags: [ { name: 'messenger.message_handler', bus: 'query.bus' } ]

    application_query_result:
        namespace: Enraged\Xenomorph\Application\QueryResult\
        autowire: true
        autoconfigure: false
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/QueryResult/**/*Result.php'

    # APPLICATION/EVENT/BUS
    application_events:
        namespace: Enraged\Xenomorph\Application\Event\
        autowire: false
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Event/'

    application_event_handlers:
        namespace: Enraged\Xenomorph\Application\EventHandler\
        autowire: true
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/EventHandler/'
        tags: [ { name: 'messenger.message_handler', bus: 'application_event.bus' } ]

    Enraged\Xenomorph\Application\Infrastructure\BUS\ApplicationEventBusInterface: '@Enraged\Xenomorph\Infrastructure\BUS\ApplicationEventBus'

    # INFRASTRUCTURE/DBAL
    Enraged\Xenomorph\Application\Infrastructure\DBAL\Example\DomainObjectDbalInterface: '@Enraged\Xenomorph\Infrastructure\DBAL\Example\DomainObjectDbal'

