services:
    domain:
        namespace: Enraged\Xenomorph\Domain\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/'
        autowire: false
        autoconfigure: false
        exclude:
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/**/*Specification.php'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/**/*Service.php'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/Event/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/EventHandler/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/Assertion/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/Exception/'

    domain_events:
        namespace: Enraged\Xenomorph\Domain\Event\
        autowire: false
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/Event/'

    domain_event_handlers:
        namespace: Enraged\Xenomorph\Domain\EventHandler\
        autowire: true
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/EventHandler/'
        tags: [ { name: 'messenger.message_handler', bus: 'domain_event.bus' } ]

    Enraged\Xenomorph\Domain\DomainEventBusInterface: '@Enraged\Xenomorph\Infrastructure\BUS\DomainEventBus'

    domain_specifictions:
        namespace: Enraged\Xenomorph\Domain\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/**/*Specification.php'
        autowire: true

    domain_services:
        namespace: Enraged\Xenomorph\Domain\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Domain/**/*Service.php'
        autowire: true

    # INFRASTRUCTURE/ORM
    Enraged\Xenomorph\Domain\Example\DomainObjectInterface:  '@Enraged\Xenomorph\Infrastructure\ORM\Example\DomainObjectRepository'