services:

    interactions:
        namespace: Enraged\Xenomorph\Interactions\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Interactions/'
        autowire: true
        autoconfigure: true
        exclude:
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Interactions/Assertion/'
            - '%kernel.project_dir%/src/Enraged/Xenomorph/Interactions/Exception/'

    # WEB
    interactions_web_queries:
        namespace: Enraged\Xenomorph\Interactions\Web\Query\
        autowire: false
        autoconfigure: false
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Interactions/Web/Query/'

    interactions_web_query_result:
        namespace: Enraged\Xenomorph\Interactions\Web\QueryResult\
        autowire: true
        autoconfigure: false
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Interactions/Web/QueryResult/**/*Result.php'

    interactions_web_controllers:
        namespace: Enraged\Xenomorph\Interactions\Web\Controller\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Interactions/Web/Controller/'
        tags: [ 'controller.service_arguments' ]