imports:
    - { resource: layers/ }

services:
    application_fixtures:
        namespace: Enraged\Xenomorph\Application\Fixtures\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Fixtures/*Fixtures.php'
        autowire: true

    application_fixtures_contexts:
        namespace: Enraged\Xenomorph\Application\Fixtures\Context\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Fixtures/Context/**/*Context.php'
        autowire: true
        shared: false
        lazy: true

    # FIXTURES
    Enraged\Xenomorph\Application\Fixtures\DevFixtures:
        public: true
        autowire: true

    # INFRASTRUCTURE/FAKER
    Enraged\Xenomorph\Application\Infrastructure\Faker\FakerInterface: '@Enraged\Xenomorph\Infrastructure\Faker\Faker'