imports:
    - { resource: layers/ }

services:
    _defaults:
        autowire: false
        autoconfigure: false

    # INFRASTRUCTURE/CALENDAR
    Enraged\Xenomorph\Infrastructure\Calendar\InMemoryCalendar: ~
    Enraged\Xenomorph\Application\Infrastructure\Calendar\ApplicationCalendarInterface: '@Enraged\Xenomorph\Infrastructure\Calendar\InMemoryCalendar'
    Enraged\Xenomorph\Infrastructure\Calendar\InfrastructureCalendarInterface: '@Enraged\Xenomorph\Infrastructure\Calendar\InMemoryCalendar'

    # INFRASTRUCTURE/HTTP
    Enraged\Xenomorph\Infrastructure\HTTP\Client\HttpClientInterface:
        class: 'Enraged\Xenomorph\Infrastructure\HTTP\Client\InMemoryHttpClient'

    application_fixtures:
        namespace: Enraged\Xenomorph\Application\Fixtures\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Fixtures/*Fixtures.php'
        autowire: true
        autoconfigure: true

    application_fixtures_contexts:
        namespace: Enraged\Xenomorph\Application\Fixtures\Context\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Fixtures/Context/**/*Context.php'
        autowire: true
        autoconfigure: false
        shared: false
        lazy: true

    # FIXTURES
    Enraged\Xenomorph\Application\Fixtures\DevFixtures:
        public: true
        autowire: true

    # INFRASTRUCTURE/FAKER
    Enraged\Xenomorph\Application\Infrastructure\Faker\FakerInterface: '@Enraged\Xenomorph\Infrastructure\Faker\Faker'