imports:
    - { resource: layers/ }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: false
        autoconfigure: false

    # CALENDAR
    Enraged\Xenomorph\CalendarInterface: '@Enraged\Xenomorph\Infrastructure\Calendar\Calendar'

    # BUS
    Enraged\Xenomorph\CommandBusInterface: '@Enraged\Xenomorph\Infrastructure\BUS\CommandBus'
    Enraged\Xenomorph\QueryBusInterface: '@Enraged\Xenomorph\Infrastructure\BUS\QueryBus'

    # STORAGE
    Enraged\Xenomorph\StorageFilesystemInterface: '@Enraged\Xenomorph\Infrastructure\Storage\Filesystem\StorageFilesystem'
    Enraged\Xenomorph\TemporaryFilesystemInterface: '@Enraged\Xenomorph\Infrastructure\Storage\Filesystem\TemporaryFilesystem'