imports:
    - { resource: layers/ }

services:
    _defaults:
        autowire: false
        autoconfigure: false

    # INFRASTRUCTURE/BUS
    Enraged\Xenomorph\Infrastructure\BUS\CommandBus:
        class: Enraged\Xenomorph\Infrastructure\BUS\CommandBus
        autowire: true
        public: true
    Enraged\Xenomorph\Infrastructure\BUS\QueryBus:
        class: Enraged\Xenomorph\Infrastructure\BUS\QueryBus
        autowire: true
        public: true

    # INFRASTRUCTURE/CALENDAR
    Enraged\Xenomorph\Infrastructure\Calendar\InMemoryCalendar: ~
    Enraged\Xenomorph\CalendarInterface: '@Enraged\Xenomorph\Infrastructure\Calendar\InMemoryCalendar'

    # INFRASTRUCTURE/STORAGE
    Enraged\Xenomorph\StorageFilesystemInterface:
        class: Enraged\Xenomorph\Infrastructure\Storage\Filesystem\StorageFilesystem
        public: true
        arguments:
          [ '@Enraged\Xenomorph\Infrastructure\Storage\Adapter\StorageAdapter' ]

    Enraged\Xenomorph\TemporaryFilesystemInterface:
        class: Enraged\Xenomorph\Infrastructure\Storage\Filesystem\TemporaryFilesystem
        public: true
        arguments:
          [ '@Enraged\Xenomorph\Infrastructure\Storage\Adapter\TemporaryAdapter' ]

    # INFRASTRUCTURE/HTTP
    Enraged\Xenomorph\Infrastructure\HTTP\Client\HttpClientInterface:
        class: 'Enraged\Xenomorph\Infrastructure\HTTP\Client\InMemoryHttpClient'

    # INFRASTRUCTURE/FAKER
    Enraged\Xenomorph\Application\Infrastructure\Faker\FakerInterface: '@Enraged\Xenomorph\Infrastructure\Faker\Faker'

    # APPLICATION/FIXTURES
    application_fixtures:
        namespace: Enraged\Xenomorph\Application\Fixtures\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Fixtures/*Fixtures.php'
        autowire: true

    application_fixtures_contexts:
        namespace: Enraged\Xenomorph\Application\Fixtures\Context\
        resource: '%kernel.project_dir%/src/Enraged/Xenomorph/Application/Fixtures/Context/**/*Context.php'
        autowire: true
        shared: false
        lazy: true

    Enraged\Xenomorph\Application\Fixtures\DevFixtures:
        public: true
        autowire: true